version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password99
      POSTGRES_DB: vectordb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
